name = "harare-metro"
compatibility_date = "2025-05-01"
main = "./worker/index.js"

# Assets configuration for React SPA
[assets]
directory = "./dist"
binding = "__STATIC_CONTENT"

# Production Environment Variables (Default)
[vars]
NODE_ENV = "production"
USE_FALLBACK_CONFIG = "false"
LOG_LEVEL = "info"
# Supabase Configuration
VITE_SUPABASE_URL = "https://oybatvdffsbaxwuxfetz.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YmF0dmRmZnNiYXh3dXhmZXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTA2MjgsImV4cCI6MjA3MzE2NjYyOH0.tLr6-BXM9LvrpmR99ZPcDP_8I0p5EfNvnpX0QAl6plo"
# Role-based access configuration
ROLES_ENABLED = "true"
DEFAULT_ROLE = "creator"
ADMIN_ROLES = "admin,super_admin,moderator"
CREATOR_ROLES = "creator,business-creator,author"

# Production KV Namespaces - Multi-tier storage architecture
# System configuration (app settings, limits)
[[kv_namespaces]]
binding = "HM_CONFIGURATIONS"
id = "02c8cf6e4a6447518dd592782cfe0f63"
preview_id = "02c8cf6e4a6447518dd592782cfe0f63"

# Cache storage (articles cache)
[[kv_namespaces]]
binding = "HM_CACHE_STORAGE"
id = "bc0a8ad20f054043a9f68032276048ba"
preview_id = "bc0a8ad20f054043a9f68032276048ba"

# News content storage (feeds, categories, keywords, tags)
[[kv_namespaces]]
binding = "HM_NEWS_STORAGE"
id = "465b7b0df847411098cc369619a690c5"
preview_id = "465b7b0df847411098cc369619a690c5"

# Cache configuration (cache settings, TTL, strategies)  
[[kv_namespaces]]
binding = "HM_CACHE_CONFIG"
id = "ec38f5bde010400e9bdd5927cb7a9910"
preview_id = "ec38f5bde010400e9bdd5927cb7a9910"

# Fast retrieval storage (likes, bookmarks, saves)
[[kv_namespaces]]
binding = "HM_USER_STORAGE"
id = "28448bdb9dd041dcaaefe292a7651c8a"
preview_id = "28448bdb9dd041dcaaefe292a7651c8a"

# Production D1 Database - Articles with slugs and content
[[d1_databases]]
binding = "ARTICLES_DB" 
database_name = "hararemetro_articles"
database_id = "70d94fe9-4a78-4926-927b-e88e37141a54"

# Production Analytics Engine - THE CORRECT 3 DATASETS
[[analytics_engine_datasets]]
binding = "CATEGORY_CLICKS"
dataset = "category_clicks"

[[analytics_engine_datasets]]
binding = "NEWS_INTERACTIONS"
dataset = "news_interactions"

[[analytics_engine_datasets]]
binding = "SEARCH_QUERIES"
dataset = "search_queries"

# Cron Triggers for Background Refresh
[triggers]
crons = ["0 * * * *"]

# Smart Placement for Global Performance
[placement]
mode = "smart"

# Production Routes
[[routes]]
pattern = "www.hararemetro.co.zw/*"
zone_name = "hararemetro.co.zw"

[[routes]]
pattern = "hararemetro.co.zw/*"
zone_name = "hararemetro.co.zw"

# Preview Environment (for local development)
[env.preview]
name = "harare-metro-preview"

[env.preview.vars]
NODE_ENV = "development"
USE_FALLBACK_CONFIG = "true"
LOG_LEVEL = "debug"
CLOUDFLARE_IMAGES_ACCOUNT_ID = "125a2dfbc21f76a25c980609609e8218"
CLOUDFLARE_IMAGES_TOKEN = "pVe0DAJWrCvXIcm7BzAymwR0vW4-oBF9VGiODLJN"
# Supabase Configuration
VITE_SUPABASE_URL = "https://oybatvdffsbaxwuxfetz.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YmF0dmRmZnNiYXh3dXhmZXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTA2MjgsImV4cCI6MjA3MzE2NjYyOH0.tLr6-BXM9LvrpmR99ZPcDP_8I0p5EfNvnpX0QAl6plo"
# Role-based access configuration
ROLES_ENABLED = "true"
DEFAULT_ROLE = "creator"
ADMIN_ROLES = "admin,super_admin,moderator"
CREATOR_ROLES = "creator,business-creator,author"

# Preview KV Namespaces - Multi-tier storage architecture (same as prod)
# System configuration (app settings, limits)
[[env.preview.kv_namespaces]]
binding = "HM_CONFIGURATIONS"
id = "02c8cf6e4a6447518dd592782cfe0f63"
preview_id = "02c8cf6e4a6447518dd592782cfe0f63"

# Cache storage (articles cache)
[[env.preview.kv_namespaces]]
binding = "HM_CACHE_STORAGE"
id = "bc0a8ad20f054043a9f68032276048ba"
preview_id = "bc0a8ad20f054043a9f68032276048ba"

# News content storage (feeds, categories, keywords, tags)
[[env.preview.kv_namespaces]]
binding = "HM_NEWS_STORAGE"
id = "465b7b0df847411098cc369619a690c5"
preview_id = "465b7b0df847411098cc369619a690c5"

# Cache configuration (cache settings, TTL, strategies)  
[[env.preview.kv_namespaces]]
binding = "HM_CACHE_CONFIG"
id = "ec38f5bde010400e9bdd5927cb7a9910"
preview_id = "ec38f5bde010400e9bdd5927cb7a9910"

# Fast retrieval storage (likes, bookmarks, saves)
[[env.preview.kv_namespaces]]
binding = "HM_USER_STORAGE"
id = "28448bdb9dd041dcaaefe292a7651c8a"
preview_id = "28448bdb9dd041dcaaefe292a7651c8a"

# Preview D1 Database - Articles with slugs and content
[[env.preview.d1_databases]]
binding = "ARTICLES_DB"
database_name = "hararemetro_articles"
database_id = "70d94fe9-4a78-4926-927b-e88e37141a54"

# Preview Analytics Engine - Same as production for consistency
[[env.preview.analytics_engine_datasets]]
binding = "CATEGORY_CLICKS"
dataset = "category_clicks"

[[env.preview.analytics_engine_datasets]]
binding = "NEWS_INTERACTIONS"
dataset = "news_interactions"

[[env.preview.analytics_engine_datasets]]
binding = "SEARCH_QUERIES"
dataset = "search_queries"
