name = "harare-metro"
compatibility_date = "2024-05-01"
main = "./worker/index.js"

[assets]
directory = "./dist/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "NEWS_STORAGE"
id = "472195d9dcb948b7a73c10b2716375ca"
preview_id = "8c7b7c28e9fa4abc971935876cf9ca26"

[triggers]
crons = ["0 */6 * * *"]

[placement]
mode = "smart"