name = "harare-metro"
main = "worker.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[site]
bucket = "./dist"
include = ["**/*"]
exclude = []

# Production environment
[[kv_namespaces]]
binding = "NEWS_STORAGE" 
id = "8c0d18bb55514ab8a5267688c19ed0a1"

[env.production]
name = "harare-metro"
routes = [
  { pattern = "hararemetro.co.zw", custom_domain = true }
]
[[env.production.kv_namespaces]]
binding = "NEWS_STORAGE"
id = "8c0d18bb55514ab8a5267688c19ed0a1"

# Staging environment
[env.staging]
name = "harare-metro-staging"
[[env.staging.kv_namespaces]]
binding = "NEWS_STORAGE"
id = "8285d3e2d6a44bbb86df44b17555d04f"

[triggers]
crons = ["0 * * * *"]

[build]
command = "npm run build"
watch_dir = "src"

[rules]
type = "ESModule"
fallthrough = true

[node_compat]
enabled = true