name = "harare-metro-worker"
main = "worker.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

# KV namespace for storing articles
[[kv_namespaces]]
binding = "NEWS_STORAGE"
preview_id = "f1d7dbeace544fd8a27913140179eafe"
id = "8c0d18bb55514ab8a5267688c19ed0a1"

# Cron trigger for hourly updates
[triggers]
crons = ["0 * * * *"]  # Every hour at minute 0

# Environment variables (set these in Cloudflare dashboard)
[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm run build"

# Development settings
[env.development]
name = "harare-metro-worker-dev"

[env.development.vars]
ENVIRONMENT = "development"

# Staging environment
[env.staging]
name = "harare-metro-worker-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
