-- Add pulse_summary column to articles table
-- Pulse AI summaries are 150-character quick summaries generated by Deepseek AI

ALTER TABLE articles ADD COLUMN pulse_summary TEXT;

-- Create index for querying articles without Pulse summaries
CREATE INDEX IF NOT EXISTS idx_articles_pulse_summary ON articles(pulse_summary);
